### ISSUE TITLE
Issue: Remove package-lock.json

### ISSUE THREAD

**Issue by shinevue** [Finalgoal231/finalGoal#71]
**Describe the bug**
The bug in deploy project

**To Reproduce**
In render.com, yarn command is install command.
But there is package-lock.json so render.com can't install node-module for build

**Comment by creative2113** [comment]
The issue is that on Render.com, the default command is `yarn` for installing dependencies, but your project has a `package-lock.json` file, which expects `npm` to be used.

To resolve this:

1. Update the "Build Command" in the Render.com dashboard to use `npm ci` instead of `yarn`.
2. This will ensure Render.com uses the correct package manager based on your `package-lock.json` file.

Let me know if you have any other questions, and I'll be happy to assist further.

**Comment by shinevue** [comment]
I know about that.
But project is already built
So please remove package-lock.json and push it

**Comment by creative2113** [comment]
yeah, I see.
😀😀😀

**Comment by creative2113** [comment]
Hello, @shinevue 

I removed and send pull request.
please check that and give me the feedback.

thanks
